
name: run tests on projects

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-groovy:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: run unit tests
        run: ./gradlew test
        working-directory: groovy

  test-java:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: run unit tests
        run: ./gradlew test
        working-directory: java

  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: run unit tests
        run: python test_gol.py
        working-directory: python

  test-ruby:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: run unit tests
        run: rake test
        working-directory: ruby

  test-c:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: run unit tests
        run: ./run_tests.sh
        working-directory: c

  test-golang:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: get Go 
        uses: actions/setup-go@v3

      - name: init module
        run: go mod init src/life
        working-directory: golang

      - name: run unit tests
        run: go test
        working-directory: golang
